# Generated by Django 4.1.3 on 2022-12-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
