# Generated by Django 4.1.3 on 2022-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_messages',
            field=models.BooleanField(default=False, help_text='Хотите ли вы получать письма о выходе новых изделий на свой email', verbose_name='Рассылка'),
        ),
    ]
