# Generated by Django 4.1.3 on 2022-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_send_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_messages',
            field=models.BooleanField(default=False, verbose_name='Рассылка'),
        ),
    ]
