# Generated by Django 4.1.3 on 2022-11-11 16:19

import django.core.validators
from django.db import migrations, models
import items.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('image', models.ImageField(upload_to=items.utils.image_directory_path)),
                ('weight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator('Вес не может быть отрицательным')], verbose_name='Вес(гр)')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ('id',),
            },
        ),
    ]
