# Generated by Django 4.1.3 on 2022-12-18 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 17, 25, 24, 9255), verbose_name='Дата создания'),
        ),
    ]
